import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>The Source of Hope</h1>
          {/* Add navigation or other header elements here */}
        </header>
        <main>{children}</main>
        <footer>
          <p>
            &copy; {new Date().getFullYear()} The Source of Hope. All rights
            reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
